name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run linter
      run: bun run lint

    - name: Run tests
      run: bun run test

    - name: Build project
      env:
        DATABASE_URL: "dummy"
        BETTER_AUTH_SECRET: "dummy"
        STRIPE_SECRET_KEY: "dummy"
        RESEND_API_KEY: "dummy"
      run: bun run build
